### PR TITLE
add HF model repos

### LINKED ISSUE #8: Having model repositories
Hiya 👋  I think it would be nice to link to HF model repositories next to Space ones given GH repositories are often used to host the code, and they have limitations on the file size the users can upload so weights are often hosted on HF Hub. Moreover, model repositories are better for hosting models - the model cards are often written by the model authors, linked to the dataset the model was trained on etc.
What do you think?

### PR DESCRIPTION
**Pull request by merveenoyan**
Closes #8

### CODE REVIEW

**Comment by merveenoyan** [comment]
@SkalskiP few mistakes, resolving shortly

**Comment by merveenoyan** [comment]
@SkalskiP I also added few Spaces, and replaced BLIP2 demo as it's calling a closed API instead of directly using the model, I think it's more useful to people. feel free to replace if you think otherwise though

**Comment by SkalskiP** [comment]
Hi @merveenoyan 👋🏻, I added automatic chronological sorting of models and did some cleanup, and I'm afraid we have some conflicts now. I'm really sorry but can I ask you to resolve those?

**Comment by SkalskiP** [comment]
I also noticed this ;) 

Screenshot 2024-02-28 at 18 07 40

**Comment by merveenoyan** [comment]
@SkalskiP I reordered them and solved merge conflicts, also fixed the above error, can you check?

**Comment by SkalskiP** [comment]
This is so cool, @merveenoyan! I love it! 🔥

**Pull request merged**
