### PR TITLE
Add models

### PR DESCRIPTION
**Pull request by merveenoyan**
Sorry for the previous PR 😊

### CODE REVIEW

**Comment by SkalskiP** [comment]
Thanks @merveenoyan 👋🏻 ! I didn't mention that I'd like to help the models in chronological order. But no worries. Let's merge it and I'll fix it on my side ;)

**Comment by SkalskiP** [comment]
@merveenoyan, one more question. Does OWLv2 take images and text as input?

**Comment by merveenoyan** [comment]
@SkalskiP technically it takes in text-like labels, so not very sure of adding multimodality there

**Comment by SkalskiP** [comment]
I updated it as 👁️ + 💬 ;)

**Pull request merged**
